### ISSUE TITLE
How does one create a user (through the docker environment)?

### ISSUE THREAD

**Issue by tlanc007** [drewbrew/djangoconus2018-drf-talk#11]
(Through docker)
I am able to get the webserver started and appears to be running.  However, it seems, I need to login before, I can really proceed with the demo.

So I tried creating a superuser through the docker-compose run, but I wasn't sure what command syntax is.  I tried multiple combos of:

% docker-compose run --rm web python manage.py createsuperuser
% docker-compose run --rm web manage.py createsuperuser
% docker-compose run --rm web ./manage.py createsuperuser

I tried similar combinations with test, too.

**Comment by drewbrew** [comment]
Hey @tlanc007,

You're so close to what you need.

Because I'm using pipenv to manage dependencies, you need to prefix it with `pipenv run`:

```bash
docker-compose run --rm web pipenv run python manage.py createsuperuser
```

Note that you may have to install dependencies first, in which case you have two options:

1. Drop to a shell (easier):
   ```bash
   docker-compose run --rm web bash
   pipenv install
   pipenv run ./manage.py createsuperuser
   ```
2. Do it as a one-liner:
   ```bash
   docker-compose run --rm web bash -c "pipenv install && pipenv run ./manage.py createsuperuser"
   ```

**Comment by tlanc007** [comment]
Thanks!  That was what I needed.

**Comment by drewbrew** [comment]
Glad it worked!
